Numpy Operations

In [23]:
import numpy as np

In [24]:
array = np.array([1,2,3,4])

print(f"shape of array {array.shape}")

shape of array (4,)


In [25]:
array2 = np.array(
  [[1,2,3,4],[5,6,7,8]]
  )
print(f"shape of array2 {array2.shape}")
print(f"shape of array2 {array2[0].shape}")
print(f"shape of array2 {array2[1].shape}")


shape of array2 (2, 4)
shape of array2 (4,)
shape of array2 (4,)


In [26]:
array3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
array3.shape = (3,2,3)

In [27]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [28]:
zero_array = np.zeros((3,2,3))
print(zero_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [29]:
arange_array = np.arange(15)
print(arange_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
array_a = np.array([1,2,2.5,3.5,4.6,6.8])
array_b = array_a.astype(np.float64)

print(f"Array b dtype is {array_b.dtype}")

Array b dtype is float64


Slicing

In [31]:
array_a = np.arange(20)
print(f"Array a is {array_a}")
sliced_a = array_a[10:15]
print(f"Sliced array a is {sliced_a}")

Array a is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Sliced array a is [10 11 12 13 14]


In [32]:
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
array_b = array_a[10:15].copy()

In [34]:
array_b

array([10, 11, 12, 13, 14])

Transpose Operation

In [35]:
array_for_transpose = np.array([
  [10,10,10],
  [20,20,20],
  [30,30,30]
  ]
)

print(f"Transposed a is {array_for_transpose.T}")

Transposed a is [[10 20 30]
 [10 20 30]
 [10 20 30]]


Numpy Random Func

In [38]:
np_random = np.random.rand(3,2,5)
np_random

array([[[0.72726013, 0.65606035, 0.43296852, 0.18581984, 0.19354483],
        [0.29832539, 0.06597107, 0.49544241, 0.539999  , 0.86464252]],

       [[0.71235366, 0.05490375, 0.83021096, 0.16555831, 0.18205995],
        [0.1657035 , 0.29660627, 0.88302231, 0.30325397, 0.74456114]],

       [[0.50305049, 0.42708227, 0.74265965, 0.42479975, 0.94572024],
        [0.04471559, 0.56260789, 0.90833661, 0.7767903 , 0.15742096]]])

Special Functions

In [39]:
array_for_special = np.random.rand(3,3,3)
exp_fun = np.exp(array_for_special)
log_fun = np.log(array_for_special)
log10_fun = np.log10(array_for_special)
sin = np.sin(array_for_special)

In [40]:
exp_fun,log_fun,log10_fun,sin

(array([[[2.62641081, 1.41440145, 1.48565388],
         [1.8084322 , 1.85243329, 1.67272293],
         [2.6426387 , 1.39525336, 1.8741384 ]],
 
        [[1.75624973, 2.57336404, 2.05379722],
         [2.4537049 , 1.18075355, 1.71107743],
         [1.9506676 , 1.33273508, 1.57839292]],
 
        [[2.29999931, 1.0492345 , 1.26075943],
         [1.1571982 , 1.67106511, 1.98969671],
         [1.41743609, 1.81511585, 1.23170574]]]),
 array([[[-0.03498676, -1.05927685, -0.92670731],
         [-0.52347145, -0.48369684, -0.66465147],
         [-0.02862797, -1.09938454, -0.46497783]],
 
        [[-0.57415474, -0.05634391, -0.32893419],
         [-0.10803176, -1.79484723, -0.6215277 ],
         [-0.40321014, -1.24746056, -0.7843699 ]],
 
        [[-0.1828311 , -3.03528735, -1.46225031],
         [-1.92413674, -0.66658079, -0.37399228],
         [-1.05311419, -0.51726415, -1.56829604]]]),
 array([[[-0.01519456, -0.46003809, -0.40246387],
         [-0.22734076, -0.21006687, -0.28865447],
         

Vector Operations

In [15]:
vector_1 = np.array(
  [[1,2,3,4],[5,6,7,8]]
  )

vector_2 = np.array(
  [[5,6,7,8],[9,10,11,12]]
  )

sum= vector_1 + vector_2
multiply = vector_1 * vector_2


In [16]:
print(f"Sum is {sum}")
print(f"Multiply is {multiply}")

Sum is [[ 6  8 10 12]
 [14 16 18 20]]
Multiply is [[ 5 12 21 32]
 [45 60 77 96]]


Linspace

In [41]:
data = np.linspace(1,20,20)
data

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [42]:
new_data = np.linspace(1,10,100)
new_data

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

WHERE

It takes data according to conditions:

If c is true get data from array1
If is not true get data from array2

In [46]:
array_1 = [1,2,3,4,5,6,7,8,9,10]
array_2 = [5,3,12,13,14,15,16,17,20,21]
c = [False, True, True, True, False, True,True,False,False,True]

np.where(c,array_1,array_2)

array([ 5,  2,  3,  4, 14,  6,  7, 17, 20, 10])

In [48]:
def fun_get_data_as_c(array_1,array_2,c):
  new_list = []

  for i in range(len(c)):
    if c[i]:
      new_list.append(array_1[i])
    else:
      new_list.append(array_2[i])

  
  return new_list


fun_get_data_as_c(array_1=array_1,array_2=array_2,c=c)

[5, 2, 3, 4, 14, 6, 7, 17, 20, 10]

Converting Array np.asarray

If the data already is numpy it doesn't create new array -> np.asarray()

In [49]:
random_a = np.random.rand(2,2,2)

as_array_random_a = np.asarray(random_a)
as_array_random_a

array([[[0.45672653, 0.2074035 ],
        [0.72250127, 0.49543513]],

       [[0.33803383, 0.45954344],
        [0.92772356, 0.93368239]]])

Converting array np.array

In [50]:
np_random = np.random.rand(2,2,2)

np_array_rand = np.array(np_random)
np_array_rand 

array([[[0.73531251, 0.4851354 ],
        [0.39205744, 0.019734  ]],

       [[0.31778884, 0.49515852],
        [0.76976416, 0.00662991]]])

Fancy Indexing

In [56]:
fancy_array = np.random.rand(
  3,3
)
fancy_array

array([[0.64462317, 0.87246576, 0.39383562],
       [0.13714805, 0.60865189, 0.44559593],
       [0.20105228, 0.29351854, 0.99983265]])

In [59]:
fancy_array[[0,2,1]]

array([[0.64462317, 0.87246576, 0.39383562],
       [0.20105228, 0.29351854, 0.99983265],
       [0.13714805, 0.60865189, 0.44559593]])

Bool Indexing

In [62]:
array_bool = np.array([
  "Eray",
  "Emirhan",
  "Rumeysa",
  "Dogukan",
  "Mehmet",
  "Azmi"
])

In [63]:
array_bool == "Eray"

array([ True, False, False, False, False, False])

In [64]:
array_bool != "Eray"

array([False,  True,  True,  True,  True,  True])

In [65]:
(array_bool == "Eray") | (array_bool != "Eray")

array([ True,  True,  True,  True,  True,  True])

In [66]:
(array_bool == "Eray") | (array_bool != "Rumeysa")

array([ True,  True, False,  True,  True,  True])

Flatten Array

Flattening operation open array like a dimension.

In [77]:
first_array = np.random.rand(
  2,3,4
)

In [78]:
first_array.shape

(2, 3, 4)

In [79]:
flattened_array = first_array.flatten()
flattened_array.shape

(24,)

Dimension is same but shape is different

Math Operations

In [67]:
mean_array = np.random.rand(2,2,20)
mean_array.mean()

np.float64(0.45838840504487566)

In [73]:
mean_array

array([[[0.36701979, 0.15538477, 0.18883128, 0.78063386, 0.12117921,
         0.1834474 , 0.451455  , 0.16035451, 0.8341735 , 0.56837709,
         0.00876666, 0.70678024, 0.83983614, 0.06562494, 0.41875752,
         0.67696391, 0.58093486, 0.01327259, 0.5669142 , 0.85029263],
        [0.12040053, 0.08224009, 0.30049855, 0.65707615, 0.52597887,
         0.4954475 , 0.13669597, 0.38571533, 0.95979436, 0.81644462,
         0.31050294, 0.82062701, 0.16105402, 0.04739784, 0.10946301,
         0.9536722 , 0.30898265, 0.66670203, 0.65621633, 0.45617834]],

       [[0.40551268, 0.80798681, 0.08437375, 0.89301432, 0.04994236,
         0.63829405, 0.49411838, 0.34288203, 0.84636524, 0.25456065,
         0.82756871, 0.6965187 , 0.80570028, 0.48469567, 0.59331121,
         0.83944347, 0.37126552, 0.82706411, 0.07330642, 0.83849924],
        [0.39106217, 0.3640068 , 0.14632608, 0.38959363, 0.09918834,
         0.20118789, 0.62783575, 0.06516359, 0.57529997, 0.1390133 ,
         0.78523063, 0.852323

In [68]:
mean_array.std()

np.float64(0.28945613909086854)

In [69]:
mean_array.sum()

np.float64(36.67107240359005)

In [75]:
def sum_of_array(example_array):
  sum = 0

  for i in example_array.flatten():
    sum +=i

  return sum

sum_of = sum_of_array(mean_array)
sum_of

np.float64(36.67107240359007)

In [76]:
def mean_of_array(example_array):

  mean = 0

  sum = sum_of_array(example_array)
  array_len = len(example_array.flatten())

  return sum / array_len

mean_of = mean_of_array(mean_array)
mean_of

np.float64(0.4583884050448758)

View and Copy

If view array changes main array changes,
If copy error changes main array does not changes

In [91]:
new_array = np.array([3,4,5,6,7])

view_array = new_array
copy_array = new_array.copy()

In [92]:
view_array[0] = 100
view_array

array([100,   4,   5,   6,   7])

In [94]:
copy_array[0] = 100
copy_array

array([100,   4,   5,   6,   7])

In [95]:
new_array

array([100,   4,   5,   6,   7])

In [90]:
view_array = np.array([11,12,13,14])
view_array,new_array

(array([11, 12, 13, 14]), array([3, 4, 5, 6, 7]))

Masking

In [96]:
mask_array = np.array([11,10,5,3,12])

mask = mask_array > 5
np.where(mask,mask_array,0)

array([11, 10,  0,  0, 12])

Arg Functions

In [97]:
arg_array = np.array([10,50,30])
arg_array

array([10, 50, 30])

In [102]:
max_index = np.argmax(arg_array)
min_index = np.argmin(arg_array)

In [103]:
arg_array[max_index],arg_array[min_index]

(np.int64(50), np.int64(10))

In [100]:
sorted = np.sort(arg_array)
indexed_sort = np.argsort(arg_array)

Unique Operation

In [104]:
array_for_unique = np.array([1,1,1,4,5,1,2,11,12])

unique = np.unique(array_for_unique)

In [105]:
unique

array([ 1,  2,  4,  5, 11, 12])

Nan Operations

In [106]:
long_array = np.array([
    1.2, np.nan, 3.5, 4.1, np.nan, 6.7, 7.8, np.nan, 9.0, 10.2,
    11.3, 12.5, np.nan, 14.7, 15.8, np.nan, 17.0, 18.1, np.nan, 20.3,
    21.4, np.nan, 23.6, 24.7, 25.8, np.nan, 27.0, 28.1, np.nan, 30.3,
    31.4, 32.5, np.nan, 34.7, 35.8, np.nan, 37.0, 38.1, np.nan, 40.3,
    41.4, np.nan, 43.6, 44.7, 45.8, np.nan, 47.0, 48.1, np.nan, 50.3
])

In [108]:
np.isnan(long_array)

array([False,  True, False, False,  True, False, False,  True, False,
       False, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True, False, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False,  True, False])

In [109]:
np.nanmean(long_array)

np.float64(25.822857142857142)

it gives you mean without nan

In [110]:
np.nansum(long_array)

np.float64(903.8)

it gives you sum without nan

Data Operations

In [1]:
import pandas as pd